apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: webapps   
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: manu681/backend:latest 
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb+srv://AyshaAjward:aysha123@finance.jfpwb.mongodb.net/finance-tracker?retryWrites=true&w=majority&appName=Finance
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
